feature/ICL-66 authorize patron
energywebfoundation/iam-cache-server pull request #201
Opened 2021-11-08 10:20 UTC by JGiter

2021-11-08 10:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/energywebfoundation/iam-cache-server?pullRequest=201) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/energywebfoundation/iam-cache-server?pullRequest=201) before we can accept your contribution.<br/>**6** out of **7** committers have signed the CLA.<br/><br/>:white_check_mark: Harasz<br/>:white_check_mark: hejkerooo<br/>:white_check_mark: jrhender<br/>:white_check_mark: michalziobro<br/>:white_check_mark: JGiter<br/>:white_check_mark: ahmedolaibrahim<br/>:x: kyleian<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/energywebfoundation/iam-cache-server?pullRequest=201) it.</sub>

2021-11-16 13:14 UTC, Harasz commented on src/common/isBigNumber.validator.ts
> +    return val instanceof BigNumber;
I think we should add more asserts here. Checking for format of the `val` or something

2021-11-16 13:18 UTC, Harasz commented on src/modules/claim/entities/claim.entity.ts
> +import { BadRequestException } from '@nestjs/common';
Import order

2021-11-16 13:20 UTC, Harasz commented on src/modules/staking/dtos/staking.pool.dto.ts
> +  address: string;
Don't we miss here `@ApiPropert()` decorator from `@nestjs/swagger`?

2021-11-16 13:20 UTC, Harasz commented on src/modules/staking/staking.service.ts
> +import { SchedulerRegistry } from '@nestjs/schedule';
Import order

2021-11-16 13:21 UTC, Harasz commented on src/modules/staking/staking.service.ts
> +    private schedulerRegistry: SchedulerRegistry,
```suggestion
    private readonly schedulerRegistry: SchedulerRegistry,
```

2021-11-16 13:21 UTC, Harasz commented on src/modules/staking/staking.service.ts
> +    private config: ConfigService,
```suggestion
    private readonly config: ConfigService,
```

2021-11-16 13:23 UTC, Harasz requested changes
Need changes

2022-01-04 12:05 UTC, JGiter commented
Obsolete because of https://github.com/energywebfoundation/iam-client-lib/blob/develop/src/modules/staking/staking-pool.service.ts

2022-01-04 12:05 UTC, closed without merging