bug/ICS-122 did not backwards compatible
energywebfoundation/iam-cache-server pull request #227
Opened 2021-12-08 16:07 UTC by JGiter

- Pipe which transforms DID to appropriate form

2021-12-08 16:53 UTC, jrhender reviewed
This looks like a great start! Good call on the pipe 👍 

Just need to set the `chain` in `DID` to `CHAIN_NAME` from config if it is missing, I think 👍

2021-12-09 12:37 UTC, Harasz requested changes
What about other places? I think we are querying DID in a couple of other places. In the latest migration file (1638185287373-AddChainIDToDIDs.ts) you can find all places in database where we are using DIDs.

2021-12-09 12:37 UTC, Harasz commented on src/modules/did/did.types.ts
> +      this.did = `did:${this.method}:$${this.id}`;
```suggestion
      this.did = `did:${this.method}:${this.id}`;
```
??

2021-12-09 15:46 UTC, JGiter commented
> What about other places? I think we are querying DID in a couple of other places. In the latest migration file (1638185287373-AddChainIDToDIDs.ts) you can find all places in database where we are using DIDs.

It requires more efforts to make all endpoints backward compatible. For example piping `did` query parameter of claims endpoints requires piping accompanying `IClaimIssuance`, `IClaimRequest` and `IClaimRejection`. I think it is risky to start such big changes during release @jrhender ?

2021-12-09 18:03 UTC, jrhender approved these changes
This looks good.

2021-12-09 18:05 UTC, jrhender commented
> It requires more efforts to make all endpoints backward compatible. For example piping did query parameter of claims endpoints requires piping accompanying IClaimIssuance, IClaimRequest and IClaimRejection. I think it is risky to start such big changes during release @jrhender ?

Yes, I think it's better to get this changed merged and then we make further changes if we need to.

2021-12-09 18:11 UTC, jrhender commented
Looking at `1638185287373-AddChainIDToDIDs.ts`, I think these are all the spots:
```
    // asset table
    await queryRunner.query(this.getUpUpdateSQL('asset', 'id'));
    await queryRunner.query(this.getUpUpdateSQL('asset', 'owner'));
    await queryRunner.query(this.getUpUpdateSQL('asset', `"offeredTo"`));
    await queryRunner.query(this.getUpUpdateSQL('asset', `"documentId"`));

    // assets_history table
    await queryRunner.query(
      this.getUpUpdateSQL('assets_history', `"emittedBy"`),
    );
    await queryRunner.query(
      this.getUpUpdateSQL('assets_history', `"relatedTo"`),
    );
    await queryRunner.query(this.getUpUpdateSQL('assets_history', `"assetId"`));

    // did_contact table
    await queryRunner.query(this.getUpUpdateSQL('did_contact', 'did'));
    await queryRunner.query(this.getUpUpdateSQL('did_contact', 'created_by'));

    // did_document_entity table
    await queryRunner.query(this.getUpUpdateSQL('did_document_entity', 'id'));

    // role_claim table
    await queryRunner.query(this.getUpUpdateSQL('role_claim', 'requester'));
    await queryRunner.query(this.getUpUpdateSQL('role_claim', 'subject'));
    await queryRunner.query(this.getUpUpdateSQL('role_claim', `"acceptedBy"`));
```
I think we're still not backwards compatible on the `did_contact` and `role_claim`. But I think folks are accessing those endpoints through Switchboard, which has the latest iam-client-lib, so I think we're okay to leave those 🤞

2021-12-09 18:39 UTC, JGiter commented
Ok. Will deal with rest endpoints later

2021-12-09 18:59 UTC, jrhender commented
@JGiter let's do it in a separate story if necessary, IMO. Your talents can be put to use elsewhere for now.
If @Harasz is okay with it, let's merge this one

2021-12-09 19:05 UTC, Harasz approved these changes
Fair enough, let's merge it

2021-12-09 19:06 UTC, merged