feature/ICS-134 persist rejection reason
energywebfoundation/iam-cache-server pull request #246
Opened 2021-12-14 16:14 UTC by JGiter

https://energyweb.atlassian.net/browse/ICS-134

2021-12-14 16:35 UTC, jrhender requested changes
I think we should keep it simple and let the requestor/issuer define the rejection reason. Not only does it simplify the code, it isn't realistic to have to add values to the `enum` for every possible reason for every possible use case

2021-12-14 16:35 UTC, jrhender commented on src/modules/claim/claim.types.ts
> +
I don't think this is necessary. The issuer/rejector should be able to put whatever they want
```suggestion
```

2021-12-14 16:35 UTC, jrhender commented on src/modules/claim/claim.dto.ts
> +  @IsEnum(RejectionReason)
Let's keep it simple. Maybe a max-length though would be good though. Maybe 200 char or something?
```suggestion
  @IsString()
```

2021-12-14 16:35 UTC, jrhender commented on src/modules/claim/claim.types.ts
> +  rejectionReason?: RejectionReason;
```suggestion
  rejectionReason?: string;
```

2021-12-14 16:35 UTC, jrhender commented on src/modules/claim/entities/roleClaim.entity.ts
> +  rejectionReason?: RejectionReason;
change to string

2021-12-15 10:00 UTC, jrhender commented
@JGiter why are there 295 files changed? Is this expected?

2021-12-15 10:06 UTC, JGiter commented
> @JGiter why are there 295 files changed? Is this expected?

Probably these .md left from previous build. Cleared them

2021-12-15 10:22 UTC, jrhender approved these changes
Looks good to me, thanks @JGiter 😄

2021-12-15 10:22 UTC, merged